swagger: "2.0"
info:
  title: Hello world!
  description: Example API that demonstrates REST & gRPC.
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /helloworld:
    get:
      tags:
      - example
      summary: hello example
      operationId: example#hello
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - http
  /ip:
    get:
      tags:
      - ipaddr
      summary: ip ipaddr
      description: Returns the public IP address of the requester
      operationId: ipaddr#ip
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - http
  /openapi.json:
    get:
      summary: Download ./gen/http/openapi.json
      operationId: openapi#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
