swagger: "2.0"
info:
  title: Hello world!
  description: Example API that demonstrates REST & gRPC.
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /hello/world:
    get:
      tags:
      - Example Service
      summary: Say Hello Example Service
      operationId: Example Service#Say Hello
      responses:
        "204":
          description: No Content response.
          schema:
            type: string
      schemes:
      - http
  /openapi.json:
    get:
      summary: Download ./gen/http/openapi.json
      operationId: Example Service#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
